"""
Analytics service — SQLite-backed historical store for GASUM recommendations.

Auto-saves every recommendation generated by the system.
Provides export to Excel for reporting and future forecasting.

Schema
------
  recommendations      — one row per generated plan
  routes               — one row per truck-day route
  site_snapshots       — network state at plan generation time
  manual_operations    — user-entered real-life ops outside the system
"""
from __future__ import annotations

import io
import json
import sqlite3
from datetime import date, datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from ..models.route import Recommendation

# ── Finnish public holidays (static list, extend as needed) ──────────────────
_FI_HOLIDAYS: Dict[str, str] = {
    "01-01": "New Year's Day",
    "01-06": "Epiphany",
    "04-18": "Good Friday",      # approximate — varies by year
    "04-20": "Easter Sunday",
    "04-21": "Easter Monday",
    "05-01": "Labour Day",
    "05-29": "Ascension Day",
    "06-19": "Midsummer Eve",
    "06-20": "Midsummer Day",
    "11-01": "All Saints' Day",
    "12-06": "Independence Day",
    "12-24": "Christmas Eve",
    "12-25": "Christmas Day",
    "12-26": "Boxing Day",
}

_DB_PATH = Path(__file__).parent.parent.parent / "database" / "analytics.db"

# ── DDL ───────────────────────────────────────────────────────────────────────
_DDL = """
PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS recommendations (
    id                          TEXT PRIMARY KEY,
    created_at                  TEXT NOT NULL,
    day_of_week                 TEXT,
    is_weekend                  INTEGER DEFAULT 0,
    is_holiday                  INTEGER DEFAULT 0,
    holiday_name                TEXT,

    -- Plan parameters
    objective                   TEXT,
    status                      TEXT,
    feasibility_level           TEXT,
    horizon_days                INTEGER,
    computation_time_seconds    REAL,

    -- Cost breakdown
    total_cost_eur              REAL,
    transport_cost_eur          REAL,
    handling_cost_eur           REAL,
    contingency_cost_eur        REAL,

    -- Config snapshot (prices at the time the plan was generated)
    cost_per_km_eur             REAL,
    handling_fee_eur            REAL,
    contingency_multiplier      REAL,

    -- Logistics results
    total_distance_km           REAL,
    routes_count                INTEGER,
    sites_served                INTEGER,
    critical_sites_addressed    INTEGER,
    total_mwh_moved             REAL,
    eur_per_mwh                 REAL,

    -- Risk
    solution_risk_score         REAL,
    critical_sites_at_time      INTEGER,
    warning_sites_at_time       INTEGER,

    -- Explanation / warnings stored as JSON strings
    explanation                 TEXT,
    warnings_json               TEXT,

    -- Optional free-text note added by operator
    notes                       TEXT,

    -- Operator learning signal
    operator_action             TEXT,
    operator_action_at          TEXT,
    operator_action_source      TEXT
);

CREATE TABLE IF NOT EXISTS routes (
    id                   TEXT PRIMARY KEY,
    recommendation_id    TEXT NOT NULL REFERENCES recommendations(id),
    truck_id             TEXT,
    day_index            INTEGER,
    total_distance_km    REAL,
    total_time_hours     REAL,
    num_stops            INTEGER,
    containers_delivered INTEGER,
    sites_visited        TEXT
);

CREATE TABLE IF NOT EXISTS route_stops (
    id                      INTEGER PRIMARY KEY AUTOINCREMENT,
    recommendation_id       TEXT NOT NULL REFERENCES recommendations(id),
    route_id                TEXT,
    day_index               INTEGER,
    truck_id                TEXT,
    sequence                INTEGER,
    site_id                 TEXT,
    site_name               TEXT,
    operation               TEXT,
    containers_dropped      TEXT,
    containers_picked       TEXT,
    cumulative_distance_km  REAL,
    arrival_time_hours      REAL,
    service_time_hours      REAL,
    load_full_after         INTEGER,
    load_empty_after        INTEGER
);

CREATE TABLE IF NOT EXISTS container_moves (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    recommendation_id   TEXT NOT NULL REFERENCES recommendations(id),
    day_index           INTEGER,
    truck_id            TEXT,
    container_serial    TEXT,
    from_site_id        TEXT,
    from_site_name      TEXT,
    to_site_id          TEXT,
    to_site_name        TEXT,
    move_type           TEXT
);

CREATE TABLE IF NOT EXISTS site_snapshots (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    recommendation_id   TEXT NOT NULL REFERENCES recommendations(id),
    site_id             TEXT,
    site_name           TEXT,
    site_type           TEXT,
    risk_level          TEXT,
    hours_to_critical   REAL,
    utilization_pct     REAL,
    inventory_kg        REAL,
    capacity_kg         REAL,
    trucks_visiting     TEXT
);

CREATE TABLE IF NOT EXISTS manual_operations (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at      TEXT NOT NULL,
    operation_date  TEXT,
    day_of_week     TEXT,
    is_weekend      INTEGER DEFAULT 0,
    is_holiday      INTEGER DEFAULT 0,
    holiday_name    TEXT,

    -- What happened
    description     TEXT NOT NULL,
    action_taken    TEXT,
    outcome         TEXT,

    -- Sites involved (JSON array of site IDs)
    sites_involved  TEXT,

    -- Optional cost/distance if known
    cost_eur        REAL,
    distance_km     REAL,

    -- Free text
    notes           TEXT
);
"""


# ── Holiday helpers ───────────────────────────────────────────────────────────

def _holiday_info(d: date):
    key = d.strftime("%m-%d")
    name = _FI_HOLIDAYS.get(key)
    return bool(name), name or ""


def _date_meta(d: date) -> dict:
    weekday   = d.strftime("%A")          # Monday … Sunday
    is_wknd   = d.weekday() >= 5
    is_hol, hname = _holiday_info(d)
    return {
        "day_of_week": weekday,
        "is_weekend":  int(is_wknd),
        "is_holiday":  int(is_hol),
        "holiday_name": hname or None,
    }


# ── AnalyticsService ──────────────────────────────────────────────────────────

class AnalyticsService:
    """
    Manages the analytics SQLite database.
    Instantiate once (singleton via get_analytics_service()) and reuse.
    """

    def __init__(self, db_path: Path = _DB_PATH) -> None:
        self.db_path = db_path
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    # ── DB setup ──────────────────────────────────────────────────────────────

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.executescript(_DDL)
            self._migrate(conn)

    def _migrate(self, conn: sqlite3.Connection) -> None:
        """Add columns/tables that may be missing from older DB versions."""
        migrations = [
            ("site_snapshots", "trucks_visiting", "TEXT"),
            ("routes",         "sites_visited",   "TEXT"),
            ("recommendations", "operator_action", "TEXT"),
            ("recommendations", "operator_action_at", "TEXT"),
            ("recommendations", "operator_action_source", "TEXT"),
        ]
        for table, col, col_type in migrations:
            try:
                conn.execute(f"ALTER TABLE {table} ADD COLUMN {col} {col_type}")
            except sqlite3.OperationalError:
                pass  # Column already exists

    # ── Auto-save recommendation ───────────────────────────────────────────────

    def save_recommendation(
        self,
        rec: Recommendation,
        computation_time: Optional[float] = None,
        config_snapshot: Optional[Dict[str, Any]] = None,
        site_states: Optional[List[Dict[str, Any]]] = None,
    ) -> None:
        """
        Persist *rec* to the analytics database.

        Call this right after the VRP solver returns a recommendation.

        Args:
            rec:               The Recommendation object.
            computation_time:  Solver wall-clock time in seconds.
            config_snapshot:   Dict with cost_per_km_eur, handling_fee_eur,
                               contingency_multiplier at plan time.
            site_states:       List of site dicts (id, name, type, risk_level,
                               hours_to_critical, utilization_pct, inventory_kg,
                               capacity_kg) for the network snapshot.
        """
        now = rec.created_at or datetime.utcnow()
        meta = _date_meta(now.date() if isinstance(now, datetime) else now)

        cfg = config_snapshot or {}
        contingency_cost = round(
            rec.total_cost_eur - rec.transport_cost_eur - rec.handling_cost_eur, 2
        )

        # Count critical/warning sites from snapshot
        critical_count = sum(
            1 for s in (site_states or []) if (s.get("risk_level") or "").lower() == "critical"
        )
        warning_count = sum(
            1 for s in (site_states or []) if (s.get("risk_level") or "").lower() == "warning"
        )

        with self._connect() as conn:
            # recommendations
            conn.execute(
                """
                INSERT OR REPLACE INTO recommendations (
                    id, created_at, day_of_week, is_weekend, is_holiday, holiday_name,
                    objective, status, feasibility_level, horizon_days, computation_time_seconds,
                    total_cost_eur, transport_cost_eur, handling_cost_eur, contingency_cost_eur,
                    cost_per_km_eur, handling_fee_eur, contingency_multiplier,
                    total_distance_km, routes_count, sites_served, critical_sites_addressed,
                    total_mwh_moved, eur_per_mwh,
                    solution_risk_score, critical_sites_at_time, warning_sites_at_time,
                    explanation, warnings_json
                ) VALUES (
                    :id, :created_at, :day_of_week, :is_weekend, :is_holiday, :holiday_name,
                    :objective, :status, :feasibility_level, :horizon_days, :computation_time_seconds,
                    :total_cost_eur, :transport_cost_eur, :handling_cost_eur, :contingency_cost_eur,
                    :cost_per_km_eur, :handling_fee_eur, :contingency_multiplier,
                    :total_distance_km, :routes_count, :sites_served, :critical_sites_addressed,
                    :total_mwh_moved, :eur_per_mwh,
                    :solution_risk_score, :critical_sites_at_time, :warning_sites_at_time,
                    :explanation, :warnings_json
                )
                """,
                {
                    "id":                    rec.id,
                    "created_at":            now.isoformat() if isinstance(now, datetime) else str(now),
                    "day_of_week":           meta["day_of_week"],
                    "is_weekend":            meta["is_weekend"],
                    "is_holiday":            meta["is_holiday"],
                    "holiday_name":          meta["holiday_name"],
                    "objective":             rec.objective_function,
                    "status":                rec.status.value if hasattr(rec.status, "value") else str(rec.status),
                    "feasibility_level":     rec.feasibility_level,
                    "horizon_days":          rec.horizon_days,
                    "computation_time_seconds": computation_time,
                    "total_cost_eur":        rec.total_cost_eur,
                    "transport_cost_eur":    rec.transport_cost_eur,
                    "handling_cost_eur":     rec.handling_cost_eur,
                    "contingency_cost_eur":  contingency_cost,
                    "cost_per_km_eur":       cfg.get("cost_per_km_eur"),
                    "handling_fee_eur":      cfg.get("handling_fee_eur"),
                    "contingency_multiplier": cfg.get("contingency_multiplier"),
                    "total_distance_km":     rec.total_distance_km,
                    "routes_count":          len(rec.routes),
                    "sites_served":          rec.sites_served,
                    "critical_sites_addressed": rec.critical_sites_addressed,
                    "total_mwh_moved":       rec.total_mwh_moved,
                    "eur_per_mwh":           rec.eur_per_mwh,
                    "solution_risk_score":   rec.solution_risk_score,
                    "critical_sites_at_time": critical_count,
                    "warning_sites_at_time": warning_count,
                    "explanation":           rec.explanation,
                    "warnings_json":         json.dumps(rec.warnings or []),
                },
            )

            # routes
            for route in rec.routes:
                conn.execute(
                    """
                    INSERT OR REPLACE INTO routes (
                        id, recommendation_id, truck_id, day_index,
                        total_distance_km, total_time_hours, num_stops, containers_delivered
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        route.id,
                        rec.id,
                        route.truck_id,
                        route.day_index,
                        route.total_distance_km,
                        route.total_time_hours,
                        route.num_stops,
                        getattr(route, "total_containers_delivered", 0),
                    ),
                )

            # site_snapshots
            if site_states:
                # Remove old snapshots for this rec (in case of re-save)
                conn.execute(
                    "DELETE FROM site_snapshots WHERE recommendation_id = ?", (rec.id,)
                )
                for s in site_states:
                    conn.execute(
                        """
                        INSERT INTO site_snapshots (
                            recommendation_id, site_id, site_name, site_type,
                            risk_level, hours_to_critical, utilization_pct,
                            inventory_kg, capacity_kg
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            rec.id,
                            s.get("id") or s.get("site_id"),
                            s.get("name") or s.get("site_name"),
                            s.get("site_type"),
                            s.get("risk_level"),
                            s.get("hours_to_critical"),
                            s.get("utilization_percentage") or s.get("utilization_pct"),
                            s.get("inventory_kg"),
                            s.get("capacity_kg"),
                        ),
                    )

    # ── Full-detail save (triggered by Export button) ─────────────────────────

    def save_recommendation_detail(
        self,
        rec: Recommendation,
        site_states: Optional[List[Dict[str, Any]]] = None,
        bay_serials: Optional[Dict[str, Dict[str, str]]] = None,
    ) -> None:
        """
        Save full per-stop and per-container detail for *rec*.

        Call this when the operator clicks Export — it persists richer data
        than the auto-save (which only stores summary figures).

        Args:
            rec:          The Recommendation object.
            site_states:  List of site dicts with risk/inventory state.
            bay_serials:  Nested dict {site_id: {bay_id: serial_number}} used to
                          resolve physical container serial numbers.  When provided,
                          container_moves stores the real S/N instead of bay IDs.

        Populates:
          - route_stops    (one row per truck-stop, with S/N columns)
          - container_moves (one row per container moved, with S/N)
          - site_snapshots  (refreshed with trucks_visiting column)
        """
        _sn: Dict[str, Dict[str, str]] = bay_serials or {}

        def _serial(site_id: str, bay_id: str) -> str:
            """Return serial number for a bay; fall back to bay_id."""
            return _sn.get(site_id, {}).get(bay_id) or bay_id

        with self._connect() as conn:
            # Wipe any previous detail for this rec so re-export is idempotent
            conn.execute("DELETE FROM route_stops     WHERE recommendation_id = ?", (rec.id,))
            conn.execute("DELETE FROM container_moves WHERE recommendation_id = ?", (rec.id,))

            # ── Build trucks-per-site map ─────────────────────────────────────
            trucks_per_site: Dict[str, List[str]] = {}
            for route in rec.routes:
                for stop in route.stops:
                    sid = stop.site_id or ""
                    trucks_per_site.setdefault(sid, [])
                    if route.truck_id not in trucks_per_site[sid]:
                        trucks_per_site[sid].append(route.truck_id)

            # ── Simulate truck journeys to assign real serial numbers ─────────
            # truck_load: per-truck FIFO list of (serial, from_site_id, from_site_name)
            truck_load: Dict[str, list] = {}

            derived_moves: list = []  # (day, truck, serial, from_sid, from_sname, to_sid, to_sname, move_type)

            for route in rec.routes:
                tid = route.truck_id
                if tid not in truck_load:
                    truck_load[tid] = []

                for stop in route.stops:
                    op = stop.swap_operation
                    if not op:
                        continue

                    # Drops: container comes from truck's current load (FIFO)
                    for bay_id in (op.containers_dropped or []):
                        if truck_load[tid]:
                            serial, from_sid, from_sname = truck_load[tid].pop(0)
                        else:
                            # Pre-loaded or unresolvable — use pickup-site serial
                            serial = _serial(stop.site_id, bay_id)
                            from_sid = None
                            from_sname = "pre-loaded"
                        derived_moves.append((
                            route.day_index, tid,
                            serial, from_sid, from_sname,
                            stop.site_id, stop.site_name or stop.site_id,
                            "full_delivery",
                        ))

                    # Picks: container comes from this site's bay
                    for bay_id in (op.containers_picked or []):
                        serial = _serial(stop.site_id, bay_id)
                        truck_load[tid].append((serial, stop.site_id, stop.site_name or stop.site_id))
                        # We don't record picks as moves here — they become "full_delivery"
                        # when the truck drops them at the destination

            # ── route_stops (with serial columns) ────────────────────────────
            # Build per-stop serial lists for display (what the truck picked/dropped)
            # using a second pass now that we have the journey simulation above.
            # Simpler approach: store original bay IDs resolved to serials directly.
            for route in rec.routes:
                for stop in route.stops:
                    op = stop.swap_operation
                    has_activity = op and (op.containers_dropped or op.containers_picked)
                    if has_activity:
                        op_text = (
                            f"drop={len(op.containers_dropped or [])} "
                            f"pick={len(op.containers_picked or [])}"
                        )
                        # Resolve serials for display
                        dropped_display = ", ".join(
                            _serial(stop.site_id, bid) for bid in (op.containers_dropped or [])
                        ) or None
                        picked_display = ", ".join(
                            _serial(stop.site_id, bid) for bid in (op.containers_picked or [])
                        ) or None
                    else:
                        op_text = "transit"
                        dropped_display = None
                        picked_display = None

                    conn.execute(
                        """
                        INSERT INTO route_stops (
                            recommendation_id, route_id, day_index, truck_id, sequence,
                            site_id, site_name, operation,
                            containers_dropped, containers_picked,
                            cumulative_distance_km, arrival_time_hours, service_time_hours,
                            load_full_after, load_empty_after
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            rec.id, route.id, route.day_index, route.truck_id, stop.sequence,
                            stop.site_id, stop.site_name or stop.site_id, op_text,
                            dropped_display, picked_display,
                            round(stop.cumulative_distance_km, 2),
                            round(stop.arrival_time_hours, 3),
                            round(stop.service_time_hours, 3),
                            stop.load_full_after,
                            stop.load_empty_after,
                        ),
                    )

            # ── container_moves ───────────────────────────────────────────────
            for day, tid, serial, from_sid, from_sname, to_sid, to_sname, move_type in derived_moves:
                conn.execute(
                    """
                    INSERT INTO container_moves (
                        recommendation_id, day_index, truck_id,
                        container_serial, from_site_id, from_site_name,
                        to_site_id, to_site_name, move_type
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (rec.id, day, tid, serial, from_sid, from_sname, to_sid, to_sname, move_type),
                )

            # ── site_snapshots (with trucks_visiting) ─────────────────────────
            if site_states:
                conn.execute(
                    "DELETE FROM site_snapshots WHERE recommendation_id = ?", (rec.id,)
                )
                for s in site_states:
                    sid = s.get("id") or s.get("site_id")
                    trucks_here = trucks_per_site.get(sid or "", [])
                    conn.execute(
                        """
                        INSERT INTO site_snapshots (
                            recommendation_id, site_id, site_name, site_type,
                            risk_level, hours_to_critical, utilization_pct,
                            inventory_kg, capacity_kg, trucks_visiting
                        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            rec.id,
                            sid,
                            s.get("name") or s.get("site_name"),
                            s.get("site_type"),
                            s.get("risk_level"),
                            s.get("hours_to_critical"),
                            s.get("utilization_percentage") or s.get("utilization_pct"),
                            s.get("inventory_kg"),
                            s.get("capacity_kg"),
                            ", ".join(trucks_here) if trucks_here else None,
                        ),
                    )

    # ── Manual operations ─────────────────────────────────────────────────────

    def add_manual_operation(
        self,
        description: str,
        operation_date: Optional[str] = None,
        action_taken: Optional[str] = None,
        outcome: Optional[str] = None,
        sites_involved: Optional[List[str]] = None,
        cost_eur: Optional[float] = None,
        distance_km: Optional[float] = None,
        notes: Optional[str] = None,
    ) -> int:
        """Insert a manual real-life operation entry. Returns the new row id."""
        now  = datetime.utcnow()
        d    = date.fromisoformat(operation_date) if operation_date else now.date()
        meta = _date_meta(d)

        with self._connect() as conn:
            cur = conn.execute(
                """
                INSERT INTO manual_operations (
                    created_at, operation_date, day_of_week, is_weekend, is_holiday, holiday_name,
                    description, action_taken, outcome, sites_involved,
                    cost_eur, distance_km, notes
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    now.isoformat(),
                    d.isoformat(),
                    meta["day_of_week"],
                    meta["is_weekend"],
                    meta["is_holiday"],
                    meta["holiday_name"],
                    description,
                    action_taken,
                    outcome,
                    json.dumps(sites_involved or []),
                    cost_eur,
                    distance_km,
                    notes,
                ),
            )
            return cur.lastrowid  # type: ignore[return-value]

    def list_manual_operations(self) -> List[Dict[str, Any]]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM manual_operations ORDER BY operation_date DESC"
            ).fetchall()
            return [dict(r) for r in rows]

    # ── Query helpers ─────────────────────────────────────────────────────────

    def list_recommendations(self, limit: int = 100) -> List[Dict[str, Any]]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT * FROM recommendations ORDER BY created_at DESC LIMIT ?", (limit,)
            ).fetchall()
            return [dict(r) for r in rows]

    def get_recommendation(self, rec_id: str) -> Optional[Dict[str, Any]]:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM recommendations WHERE id = ?", (rec_id,)
            ).fetchone()
            return dict(row) if row else None

    def record_operator_action(
        self,
        rec_id: str,
        action: str,
        action_at: Optional[datetime] = None,
        source: str = "ui",
    ) -> bool:
        """Persist operator feedback labels for future recommendation learning."""
        action_at = action_at or datetime.utcnow()
        with self._connect() as conn:
            cur = conn.execute(
                """
                UPDATE recommendations
                   SET status = ?,
                       operator_action = ?,
                       operator_action_at = ?,
                       operator_action_source = ?
                 WHERE id = ?
                """,
                (
                    action,
                    action,
                    action_at.isoformat(),
                    source,
                    rec_id,
                ),
            )
            return bool(cur.rowcount)

    def rebuild_risk_counts_from_snapshots(self) -> int:
        """Backfill current risk counts from stored site snapshots where available."""
        with self._connect() as conn:
            rows = conn.execute(
                """
                SELECT recommendation_id,
                       SUM(CASE WHEN lower(coalesce(risk_level, '')) = 'critical' THEN 1 ELSE 0 END) AS critical_count,
                       SUM(CASE WHEN lower(coalesce(risk_level, '')) = 'warning' THEN 1 ELSE 0 END) AS warning_count
                  FROM site_snapshots
              GROUP BY recommendation_id
                """
            ).fetchall()
            for row in rows:
                conn.execute(
                    """
                    UPDATE recommendations
                       SET critical_sites_at_time = ?,
                           warning_sites_at_time = ?
                     WHERE id = ?
                    """,
                    (
                        int(row["critical_count"] or 0),
                        int(row["warning_count"] or 0),
                        row["recommendation_id"],
                    ),
                )
            return len(rows)

    # ── Excel export (full analytics) ────────────────────────────────────────

    def export_analytics_excel(self, limit: int = 500) -> bytes:
        """
        Export the full analytics database to a multi-sheet Excel workbook.
        Returns raw bytes.
        """
        HDR_FILL = PatternFill("solid", fgColor="1E3A5F")
        HDR_FONT = Font(name="Calibri", bold=True, color="FFFFFF", size=10)
        BODY_FONT = Font(name="Calibri", size=10)
        EVEN_FILL = PatternFill("solid", fgColor="EEF2F7")
        THIN = Side(style="thin", color="CCCCCC")
        BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

        def hdr(ws, r, c, v):
            cell = ws.cell(row=r, column=c, value=v)
            cell.fill = HDR_FILL; cell.font = HDR_FONT; cell.border = BORDER
            cell.alignment = Alignment(horizontal="center", wrap_text=True)

        def body(ws, r, c, v, even=False):
            cell = ws.cell(row=r, column=c, value=v)
            cell.font = BODY_FONT; cell.border = BORDER
            if even: cell.fill = EVEN_FILL

        def auto_width(ws):
            for col in ws.columns:
                w = max(len(str(c.value or "")) for c in col)
                ws.column_dimensions[get_column_letter(col[0].column)].width = max(10, min(w + 3, 40))

        wb = Workbook()

        # ── Sheet: Recommendations ────────────────────────────────────────────
        ws = wb.active
        ws.title = "Recommendations"
        ws.sheet_view.showGridLines = False
        recs = self.list_recommendations(limit)
        rec_headers = [
            "ID", "Created At", "Day of Week", "Weekend?", "Holiday?", "Holiday Name",
            "Objective", "Status", "Feasibility", "Horizon (days)", "Computation (s)",
            "Total Cost (EUR)", "Transport Cost (EUR)", "Handling Cost (EUR)", "Contingency (EUR)",
            "Cost/km (EUR)", "Handling Fee (EUR)", "Contingency Multiplier",
            "Distance (km)", "Routes", "Sites Served", "Critical Addressed",
            "MWh Moved", "EUR/MWh", "Risk Score", "Critical Sites", "Warning Sites",
            "Operator Action", "Operator Action At", "Operator Action Source",
        ]
        for c, h in enumerate(rec_headers, 1):
            hdr(ws, 1, c, h)
        for i, r in enumerate(recs, 2):
            even = (i % 2 == 0)
            for c, key in enumerate([
                "id", "created_at", "day_of_week", "is_weekend", "is_holiday", "holiday_name",
                "objective", "status", "feasibility_level", "horizon_days", "computation_time_seconds",
                "total_cost_eur", "transport_cost_eur", "handling_cost_eur", "contingency_cost_eur",
                "cost_per_km_eur", "handling_fee_eur", "contingency_multiplier",
                "total_distance_km", "routes_count", "sites_served", "critical_sites_addressed",
                "total_mwh_moved", "eur_per_mwh", "solution_risk_score",
                "critical_sites_at_time", "warning_sites_at_time",
                "operator_action", "operator_action_at", "operator_action_source",
            ], 1):
                body(ws, i, c, r.get(key), even)
        auto_width(ws)

        # ── Sheet: Routes ─────────────────────────────────────────────────────
        ws2 = wb.create_sheet("Routes")
        ws2.sheet_view.showGridLines = False
        with self._connect() as conn:
            route_rows = conn.execute(
                "SELECT * FROM routes ORDER BY recommendation_id, day_index"
            ).fetchall()
        route_headers = [
            "Route ID", "Recommendation ID", "Truck", "Day",
            "Distance (km)", "Time (h)", "Stops", "Containers Delivered", "Sites Visited",
        ]
        for c, h in enumerate(route_headers, 1):
            hdr(ws2, 1, c, h)
        for i, r in enumerate(route_rows, 2):
            even = (i % 2 == 0)
            for c, key in enumerate([
                "id", "recommendation_id", "truck_id", "day_index",
                "total_distance_km", "total_time_hours", "num_stops",
                "containers_delivered", "sites_visited",
            ], 1):
                body(ws2, i, c, r[key], even)
        auto_width(ws2)

        # ── Sheet: Route Stops ────────────────────────────────────────────────
        ws_stops = wb.create_sheet("Route Stops")
        ws_stops.sheet_view.showGridLines = False
        with self._connect() as conn:
            stop_rows = conn.execute(
                """SELECT * FROM route_stops
                   ORDER BY recommendation_id, day_index, truck_id, sequence"""
            ).fetchall()
        stop_headers = [
            "Rec ID", "Route ID", "Day", "Truck", "Seq",
            "Site ID", "Site Name", "Operation",
            "Containers Dropped (serials)", "Containers Picked (serials)",
            "Cumul. Distance (km)", "Arrival Time (h)", "Service Time (h)",
            "Load Full After", "Load Empty After",
        ]
        for c, h in enumerate(stop_headers, 1):
            hdr(ws_stops, 1, c, h)
        for i, r in enumerate(stop_rows, 2):
            even = (i % 2 == 0)
            for c, key in enumerate([
                "recommendation_id", "route_id", "day_index", "truck_id", "sequence",
                "site_id", "site_name", "operation",
                "containers_dropped", "containers_picked",
                "cumulative_distance_km", "arrival_time_hours", "service_time_hours",
                "load_full_after", "load_empty_after",
            ], 1):
                body(ws_stops, i, c, r[key], even)
        auto_width(ws_stops)

        # ── Sheet: Container Moves ────────────────────────────────────────────
        ws_moves = wb.create_sheet("Container Moves")
        ws_moves.sheet_view.showGridLines = False
        with self._connect() as conn:
            move_rows = conn.execute(
                """SELECT * FROM container_moves
                   ORDER BY recommendation_id, day_index, truck_id"""
            ).fetchall()
        move_headers = [
            "Rec ID", "Day", "Truck", "Container Serial",
            "From Site ID", "From Site Name", "To Site ID", "To Site Name", "Move Type",
        ]
        for c, h in enumerate(move_headers, 1):
            hdr(ws_moves, 1, c, h)
        for i, r in enumerate(move_rows, 2):
            even = (i % 2 == 0)
            for c, key in enumerate([
                "recommendation_id", "day_index", "truck_id", "container_serial",
                "from_site_id", "from_site_name", "to_site_id", "to_site_name", "move_type",
            ], 1):
                body(ws_moves, i, c, r[key], even)
        auto_width(ws_moves)

        # ── Sheet: Site Snapshots ─────────────────────────────────────────────
        ws_sites = wb.create_sheet("Site Snapshots")
        ws_sites.sheet_view.showGridLines = False
        with self._connect() as conn:
            site_rows = conn.execute(
                "SELECT * FROM site_snapshots ORDER BY recommendation_id, site_name"
            ).fetchall()
        site_headers = [
            "Rec ID", "Site ID", "Site Name", "Type",
            "Risk Level", "Hours to Critical", "Utilization (%)",
            "Inventory (kg)", "Capacity (kg)", "Trucks Visiting",
        ]
        for c, h in enumerate(site_headers, 1):
            hdr(ws_sites, 1, c, h)
        for i, r in enumerate(site_rows, 2):
            even = (i % 2 == 0)
            for c, key in enumerate([
                "recommendation_id", "site_id", "site_name", "site_type",
                "risk_level", "hours_to_critical", "utilization_pct",
                "inventory_kg", "capacity_kg", "trucks_visiting",
            ], 1):
                body(ws_sites, i, c, r[key], even)
        auto_width(ws_sites)

        # ── Sheet: Manual Operations ──────────────────────────────────────────
        ws3 = wb.create_sheet("Manual Operations")
        ws3.sheet_view.showGridLines = False
        manual = self.list_manual_operations()
        manual_headers = [
            "ID", "Created At", "Operation Date", "Day of Week", "Weekend?", "Holiday?", "Holiday Name",
            "Description", "Action Taken", "Outcome", "Sites Involved", "Cost (EUR)", "Distance (km)", "Notes",
        ]
        for c, h in enumerate(manual_headers, 1):
            hdr(ws3, 1, c, h)
        for i, r in enumerate(manual, 2):
            even = (i % 2 == 0)
            for c, key in enumerate([
                "id", "created_at", "operation_date", "day_of_week",
                "is_weekend", "is_holiday", "holiday_name",
                "description", "action_taken", "outcome", "sites_involved",
                "cost_eur", "distance_km", "notes",
            ], 1):
                body(ws3, i, c, r.get(key), even)
        auto_width(ws3)

        buf = io.BytesIO()
        wb.save(buf)
        return buf.getvalue()


# ── Singleton ─────────────────────────────────────────────────────────────────

_analytics_service: Optional[AnalyticsService] = None


def get_analytics_service() -> AnalyticsService:
    global _analytics_service
    if _analytics_service is None:
        _analytics_service = AnalyticsService()
    return _analytics_service
